setuptools: Disable auto discovery
The latest release of setuptools 61.0 made a breaking change[1] and
because of this change 'pip install' fails with the following error.

~~~
error: Multiple top-level packages discovered in a flat-layout:
['lib', 'spec', 'manifests', 'releasenotes'].
~~~

Users that don't set 'packages', 'py_modules', or configuration'
are still likely to observe the auto-discovery behavior, which may
halt the build if the project contains multiple directories and/or
multiple Python files directly under the project root.

To disable auto discovery, one can do below in setup.py

~~~
setuptools.setup(..,packages=[],..)
~~~

or

~~~
setuptools.setup(..,py_modules=[],..)
~~~

[1] https://github.com/pypa/setuptools/issues/3197

Note setup.py is not used to install puppet modules. However it is used
to generate a release note, thus should be fixed.

Conflicts:
	setup.py

Signed-off-by: Jiri Podivin <jpodivin@redhat.com>
Change-Id: I561abed5abd7e48ab5491fa8ecbf16341ab0a3a4
(cherry picked from commit 5a6caae06cb68333e5eae9059691f6b248a28da4)
(cherry picked from commit c0dffc21d1fde1df29bea0a583a5e9578a6dcc94)